### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/wakatime-mod#1]
# Meta

- [ ] Github repo has no description [enable here](https://github.com/NeonGamerBot-QK/wakatime-mod)

- [ ] There is no homepage! [enable here](https://github.com/NeonGamerBot-QK/wakatime-mod)

- [ ] Your default branch is not 'main' please update it. [enable here](https://github.com/NeonGamerBot-QK/wakatime-mod/settings)

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] if possible make your app docker compatible? (beta)

- [ ] if possible make your app docker compatible? (beta)

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [x] **Mark this to override & close this issue.**
